### ISSUE TITLE
Idea: MQTT instead of HTTP API

### ISSUE THREAD

**Issue by HGlab01** [MK-2001/ioBroker.go-e#161]
First of all thanks for your effort to provide this adapter!
I tried to use it to steer my PV/batteries based on the current used power.
As via HTTP polling the updates are not that often it did not really work. Therefore I am now using the MQTT API which triggers iobroker based on every change.

I think it would add additional value for the community to provide the adater based on MQTT instead of HTTP - just a thought :-)

**Comment by MK-2001** [comment]
Good idea. 
but will work only with Ann external mqtt server.
Let's see.  think it could be an idea after adapter of api v2.

**Comment by sailor25462** [comment]
Hi, I’m using mqtt with iobroker and node-red, incl a simple UI control screen for the browser. 
I had to use it because the Wallbox is in an external building, not having LAN access but only mobile internet. Works fine. However, there’s a big „but“. Since the state is sent very often and always as one complete message, data drainage is huge. If I remember correctly it’s about 200MB per day. Messages are sent every single second. For mqtt, this is insane.

**Comment by HGlab01** [comment]
> Good idea. but will work only with Ann external mqtt server. Let's see. think it could be an idea after adapter of api v2.

I created an adapter which acts as an MQTT server
https://github.com/HGlab01/ioBroker.tinymqttbroker
and I subsribe with a JS script to the topics I need from go-e
