### ISSUE TITLE
RFIDs all have the same ID

### ISSUE THREAD

**Issue by RandyAndy1** [MK-2001/ioBroker.go-e#205]
In the latest adapter version the all RDIF IDs have the same number 1.
As a consequence the RDIF and the loaded power can't be read and shown.
![1704215964352-9725e87f-71d5-4e7c-9fc0-78023baa89e5-grafik](https://github.com/MK-2001/ioBroker.go-e/assets/46190910/04efddd7-ef6c-46ae-946f-90d233efab6b)
Tested w/ Adapter Version 1.0.15 and 1.0.29

**Comment by Wildbill-Z** [comment]
Seems to be problem with goe- api v1 itself as for me
http://192.168.100.183/status (api 1)
is always showing 

`  "uby": "1",
`

where 
http://192.168.100.183/api/status (api 2)
is showing

`  "trx": 2,
`

which would be the correct id for RFID-badge.
@MK-2001 Would it be possible to show trx (api 2) instead of uby (api 1) in iobroker objects? I switched from API v1 to v2 in adapter settings but all the objects seem to keep the same. I have a go-e Gemini. But I am sure it worked with it an api v1 until 1 or 2 weeks before now.

**Comment by RandyAndy1** [comment]
I switched now to API2 in the adapter (by the way I have Hardware Version 3). To make sure that API2 is used I disabled API1 in the go-e App in "erweiterte Einstellungen". Doing so I do not have access to the wallbox indicated by a yellow warning symbol "Verbunden mit Gerät oder Dienst".
I used now also the URL http://192.168.178.67/api/status (api2, api1 disabled) and I am getting the following JSON information in the section CARD:
![grafik](https://github.com/MK-2001/ioBroker.go-e/assets/46190910/45126b8c-d90a-4d3d-9cae-d72f20ea2eb8)
Seems so that there is no ID or better the ID is set to true what makes no sense.

**Comment by Wildbill-Z** [comment]
@RandyAndy1 You have to look for "trx" in the JSON. There you will find the actual RFID-badge-number.
Unfortunately, the iobroker adapter seems to not show trx in the objects (as it does with "uby" for API v1).
In the [iobroker-Forum](https://forum.iobroker.net/post/1107407) I wrote, that I got a message about new firmware 0.56.1 in go-e-App which has something with "wrong RFID" in the fixed bugfixes. As soon I have to charge one of the cars, I will see, if the problem is solved with the new firmware as it definitely was a go-e-fault, when even the API sends the wrong ID (uby always 1).

**Comment by Wildbill-Z** [comment]
As written in the [forum-thread](https://forum.iobroker.net/post/1107849) the update to beta 0.56.1 changed the behaviour. But it seems to not show the correct number in uby, maybe the counting in the API is now starting with 0?! It actually should show a 3 (RFID badge 3) but shows a 2. Nevertheless, the charging is correctly shown in go-e.0.rfid.badges.**3**.consumption which is the important part for me. But that worked also with old "faulty" firmware.

**Comment by RandyAndy1** [comment]
Maybe I described it wrong. The ID when using a tag and place it right before the reader of the wallbox shows 0-4 (this is confirmed). I can confirm that the object called unlocked_by shows a number when I place a tag at the reader. The problem is I can't assign it to a tag in the section rfid/badges/numer/ID since this ID always have the same number (in my case 1).
A work around could be to add into this section  a adapter created ID. This also should work. But of course this is a work around and not perfect.

**Comment by Wildbill-Z** [comment]
OK, these objects are 1 for me too, even after update. But I can't say if they ever showed something else, as I didn't use them. I just use uby to check which car started to charge and consumption below the badges for cumulating the charging amount for each car/badge. And only the first one (uby) didn't work as before.

**Comment by RandyAndy1** [comment]
This was different before and each tag/batch had its own number 1 - 10. I used it to separate between cars. Seems to be that this is a bug in the go-e firmware. I confirm that go-e used 1-10  in the past. Now it seems that they are using 0-9. Strange to me is that I in the JSON file in section cards the ID is set to true. In my opinion there should be a number or better the ID of the RFID Tag.
One kore question: Why can't I get access via API2.

**Comment by Wildbill-Z** [comment]
http://192.168.178.67/api/status should be API v2 as API v1 is just IP/status
