### ISSUE TITLE
Some parameters are not writeable by default

### ISSUE THREAD

**Issue by GoClyde** [MK-2001/ioBroker.go-e#47]
**Describe the bug**  
Some parameters, that should be writeable (see API), are defined to be just readable by default.

**To Reproduce**  
1. Install adapter
2. See writeability of objects in object view
For example "ust"
![grafik](https://user-images.githubusercontent.com/85223392/120454350-17fd8980-c394-11eb-8319-4b258219505f.png)

**Expected behavior**  
All parameters, that are described in the API to be settable, should be writeable by default.

**Versions:**  
 - Adapter version: 1.04
 - JS-Controller version: 3.1.6
 - Node version: v12.20.2
 - Operating system: Linux raspberrypi 5.10.11-v71+ #1399

**Additional context**  
Following parameters are not writeable by default although they should be:
- wss
- wke
- wen
- tof
- tds
- lbr
- aho
- afi
- ama
- ust
- wak
- r1x
- dto
- nmo
- rn[a,m,r,1-9]

**Comment by MK-2001** [comment]
Hi GoClyde. Thank you for reporting that there is some behavior that is not expected. We started as fast as possible with the, in our mind, most usable attribute with the write access. And the work is currently not done at all. 

We have this topic already on our list in #12. I'ld like to close this issue because of double issue.
You mentioned in your example that ust is needed in you case. I will bring this in the next version as one of the next features. Please comment relevant topics in the issue #12.

Thank you.

**Comment by GoClyde** [comment]
Hi @MK-2001,
I tested to just edit the ust to writeable (check "Schreiben erlaubt") and it worked (the status was transferred to the app after changing the value in iobroker). So I guessed, that it would be a bug and it is not much work needed to fix it.
But when there is a several ticket for it in progress, there seems to be more changes necessary than just checking the checkbox :) 
We can close this issue.
