### ISSUE TITLE
Fehlermeldungen nach  Update von IoBroker

### ISSUE THREAD

**Issue by Jockelflo** [MK-2001/ioBroker.go-e#69]
Hallo,

folgende Fehlermeldung erhalte ich:

go-e.0 | 2021-07-11 17:52:28.074 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
-- | -- | -- | --
go-e.1 | 2021-07-11 17:52:26.224 | info | ""
go-e.1 | 2021-07-11 17:52:26.224 | error | API response validation error: [{"message":"\"value\" must be of type object","path":[],"type":"object.base","context":{"type":"object","label":"value","value":""}}]
go-e.0 | 2021-07-11 17:52:23.044 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"

Ich hatte die Adapter Admin, Vis, Web und so aktuallisiert und seitdem kommen diese Meldungen.
Grüße

**Comment by MK-2001** [comment]
Hi, 

thank you for your report. 
These issues should be solved with version 1.0.13.

Thank you

**Comment by Wildbill-Z** [comment]
@MK-2001 I updated JS-Controller to 3.3.15 (current new stable). Since then, I also receive this messages:
`
go-e.0 | 2021-08-05 18:08:40.891 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
-- | -- | -- | --
go-e.0 | 2021-08-05 18:08:10.816 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:07:40.921 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:07:10.810 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:06:40.915 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:06:10.914 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:05:40.892 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-05 18:05:11.517 | info | (8180) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"`
Installed adapter version is 1.0.15. I even stopped adapter, deleted datapoint and restarted, but with no effect. Is there anything else, I can do?

Greetings, Jürgen
